services:
  mysql:
    container_name: containerMysql
    image: eduardomiyasaki/staffwatch:bancov1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_segura
    # volumes:
    #   - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    container_name: containerSite
    image: eduardomiyasaki/staffwatch:sitev1
    volumes:
      - ./app:/app  # Mapeia a pasta local para o contêiner
    ports:
      - "3333:3333"  # Mapeia a porta do contêiner para o host
    depends_on:
      - mysql  # Garante que o MySQL esteja ativo antes do Node.js
    environment:
      DB_HOST: 44.194.151.184
      DB_USER: root
      DB_PASSWORD: senha_segura
      DB_NAME: StaffWatch

volumes:
  mysql_data:
